# Generated by Django 4.2.29 on 2026-04-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishbook", "0002_alter_ingredient_id_alter_profile_id_alter_recipe_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientAmount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("is_scalable", models.BooleanField(default=True)),
                (
                    "package_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("package_unit", models.CharField(blank=True, max_length=40)),
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_amount",
                        to="dishbook.ingredient",
                    ),
                ),
            ],
        ),
    ]
